# Generated by Django 3.1.6 on 2021-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.CharField(default='rasyidev', max_length=50),
            preserve_default=False,
        ),
    ]
